# Generated by Django 2.1.5 on 2020-06-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200627_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slider_heading',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='category',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
