# Generated by Django 2.1.5 on 2020-06-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200627_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
